Repository leanprover-community/batteries, pull requests merged in 2023-10, with the labels that each got.

#268 feat: a linter for instances that are not classes
  Std/Tactic/Lint/TypeClass.lean
  test/lintTC.lean
Labels: awaiting-review

#287 feat: lemmas relating List.zip and List.map
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#288 feat: lemmas about List.zipWith
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#290 feat: theorem characterizing Nat.gcd
  Std/Data/Nat/Gcd.lean
Labels: awaiting-review

#292 feat: lemmas about Option
  Std/Data/Option/Lemmas.lean
Labels: awaiting-review

#294 chore: delete stray List lemma
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#295 feat: lemmas about List.findIdx
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#284 chore: bump to v4.2.0-rc2
  Std/Tactic/SimpTrace.lean
  Std/Tactic/Simpa.lean
  lean-toolchain
Labels: depends on core changes

#289 feat: List.zipWithAll, that continues to the end of both lists
  Std/Data/List/Basic.lean
Labels: awaiting-review

#298 chore: upstream some logic
  Std/Data/HashMap/WF.lean
  Std/Data/List/Lemmas.lean
  Std/Data/List/Pairwise.lean
  Std/Logic.lean
Labels: awaiting-review

#299 feat: make try this suggestions fit in the suggested width
  Std/Tactic/TryThis.lean
  test/add_suggestion.lean
Labels: awaiting-review

#300 chore: bump toolchain to v4.2.0-rc3
  lean-toolchain
Labels: awaiting-review

#244 chore: upstream rfl and symm tactics
  Std.lean
  Std/Lean/Elab/Tactic.lean
  Std/Lean/Meta/Basic.lean
  Std/Tactic/Relation/Rfl.lean
  Std/Tactic/Relation/Symm.lean
  test/rfl.lean
  test/symm.lean
Labels: awaiting-review

#317 chore: automation to maintain a nightly-testing branch
  .github/nightly_bump_toolchain.yml
  .github/nightly_detect_failure.yml
  .github/nightly_merge_master.yml
Labels: awaiting-review

#267 feat: add the json% macro from ProofWidgets4
  Std.lean
  Std/Data/Json.lean
  Std/Lean/Json.lean
  test/json.lean
Labels: enhancement, awaiting-review

#318 chore: typo in #317
  .github/nightly_detect_failure.yml
Labels: awaiting-review

#215 feat: Try these
  Std/Tactic/TryThis.lean
  test/tryThis.lean
Labels: awaiting-review

#276 fix: make Fin.val_succ `dsimp`
  Std/Data/Fin/Lemmas.lean
Labels: awaiting-review

#322 chore: move workflows to correct directory
  .github/workflows/nightly_bump_toolchain.yml
  .github/workflows/nightly_detect_failure.yml
  .github/workflows/nightly_merge_master.yml
Labels: awaiting-review

#183 feat: `Bool` lemmas
  Std.lean
  Std/Data/Bool.lean
  Std/Data/List/Lemmas.lean
Labels: awaiting-author

#321 feat: Migrate #print prefix from Mathlib
  .github/workflows/build.yml
  Std.lean
  Std/Lean/Util/EnvSearch.lean
  Std/Tactic/PrintPrefix.lean
  test/print_prefix.lean
Labels: awaiting-review

#339 chore: add Option.getD_eq_iff
  Std/Data/Option/Lemmas.lean
Labels: awaiting-review
