Repository leanprover-community/batteries, pull requests merged in 2023-11, with the labels that each got.

#340 feat: lemmas characterising List.minimum?
  Std/Data/List/Lemmas.lean
  Std/Logic.lean
Labels: awaiting-review

#196 feat: more min/max lemmas for `Nat`
  Std/Data/List/Lemmas.lean
  Std/Data/Nat/Lemmas.lean
Labels: awaiting-review

#329 feat: more lemmas and perf update
  Std/Data/Bool.lean
Labels: awaiting-review

#328 feat: Int.div_nonneg_iff_of_pos
  Std/Data/Int/DivMod.lean
Labels: awaiting-review

#325 feat: lemmas characterising zipWith(All) via get?
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#238 chore: upstream left and right tactics
  Std.lean
  Std/Tactic/LeftRight.lean
  test/left_right.lean
Labels: awaiting-review

#254 chore: MVarId.isIndependentOf
  Std/Lean/Meta/Basic.lean
Labels: awaiting-review

#344 chore: upstream some classical logic lemmas
  Std/Logic.lean
Labels: awaiting-review

#259 chore: add linter for 'import Lean'
  .github/workflows/build.yml
  Std/Tactic/Exact.lean
  Std/Tactic/LeftRight.lean
  Std/Tactic/Replace.lean
Labels: awaiting-review

#195 feat: more succ/pred lemmas for `Nat`
  Std/Data/Array/Lemmas.lean
  Std/Data/List/Lemmas.lean
  Std/Data/Nat/Lemmas.lean
Labels: awaiting-review

#194 feat: more order lemmas for `Nat`
  Std/Data/Array/Init/Lemmas.lean
  Std/Data/Nat/Init/Lemmas.lean
  Std/Data/Nat/Lemmas.lean
Labels: awaiting-review

#350 chore: create nightly-testing-YYYY-MM-DD branches when nightly-testing passes CI
  .github/workflows/nightly_detect_failure.yml
Labels: awaiting-review

#349 fix: github nightly workflow shouldn't run on forks
  .github/workflows/nightly_bump_toolchain.yml
  .github/workflows/nightly_merge_master.yml
Labels: awaiting-review

#362 chore: replace 'namespace Mathlib', and lint
  .github/workflows/build.yml
  Std/Util/Cache.lean
Labels: awaiting-review

#360 feat: upstream lemmas about if-then-else
  Std/Data/List/Lemmas.lean
  Std/Data/Range/Lemmas.lean
  Std/Data/Rat/Lemmas.lean
  Std/Logic.lean
Labels: awaiting-review

#351 feat: upstream norm_cast
  Std.lean
  Std/Data/Int/Lemmas.lean
  Std/Data/Rat/Lemmas.lean
  Std/Lean/Meta/Simp.lean
  Std/Tactic/NormCast.lean
  test/norm_cast.lean
Labels: awaiting-review

#363 feat: List.enum_length
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#364 feat: Array.attach
  Std.lean
  Std/Data/Array/Basic.lean
  Std/Data/List/Basic.lean
  Std/Data/List/Init/Attach.lean
Labels: awaiting-review

#368 chore: fix MVarId.isIndependentOf
  Std/Lean/Meta/Basic.lean
Labels: awaiting-review

#367 chore: bump toolchain to v4.3.0-rc2
  .gitignore
  GNUmakefile
  Std/Classes/LawfulMonad.lean
  Std/Data/Array/Init/Lemmas.lean
  Std/Data/Char.lean
  Std/Data/Fin/Lemmas.lean
  Std/Data/Int/DivMod.lean
  Std/Data/List/Basic.lean
  Std/Data/List/Count.lean
  Std/Data/List/Lemmas.lean
  Std/Data/List/Pairwise.lean
  Std/Data/Nat/Lemmas.lean
  Std/Data/Rat/Lemmas.lean
  Std/Logic.lean
  lean-toolchain
  test/add_suggestion.lean
  test/by_contra.lean
Labels: awaiting-review

#370 chore: adjustments to runLinter so it can be used downstream
  scripts/runLinter.lean
Labels: awaiting-review

#291 chore: add @[simp] to useful lemmas about Int
  Std/Data/Int/DivMod.lean
  Std/Data/Int/Lemmas.lean
Labels: awaiting-review

#369 chore: DiscrTreeCache.mk uses insertCore not insertIfSpecific
  Std/Util/Cache.lean
Labels: awaiting-review

#375 chore: fix failure on main; something went wrong after #291
  Std/Data/Int/DivMod.lean
  Std/Data/Rat/Lemmas.lean
Labels: awaiting-review

#372 feat: simple lemmas about LE and LT
  Std/Classes/Order.lean
Labels: awaiting-review

#377 chore: fix namespacing in Std.Classes.Order
  Std/Classes/Order.lean
  Std/Data/RBMap/Alter.lean
  Std/Data/RBMap/Basic.lean
  Std/Data/RBMap/WF.lean
Labels: awaiting-review

#378 feat: add a few missing lemmas about array size
  Std/Data/Array/Lemmas.lean
Labels: awaiting-review

#247 chore: upstream run_cmd / run_tac / by_elab
  Std.lean
  Std/Tactic/RunCmd.lean
  test/run_cmd.lean
Labels: awaiting-review

#374 feat: `Fin.foldl` and `Fin.foldr`
  Std/Data/Fin/Basic.lean
Labels: awaiting-review

#373 feat: lemmas for ReaderT and StateT
  Std.lean
  Std/Control/Lemmas.lean
Labels: awaiting-review

#354 feat: Upstream the coercion arrows from mathlib, and use them in the coe delaborator
  Std/Tactic/CoeExt.lean
  test/coe.lean
Labels: awaiting-review

#345 feat: upstream 'change at' tactic
  Std.lean
  Std/Tactic/Change.lean
  test/change.lean
Labels: awaiting-review

#313 feat: Array.get_pop and List.get_dropLast
  Std/Data/Array/Lemmas.lean
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#380 chore: use minimal imports
  Std/Lean/Meta/UnusedNames.lean
  test/bitvec.lean
Labels: awaiting-review

#382 feat: some quantifier lemmas
  Std/Logic.lean
Labels: awaiting-review

#381 feat: missing ext lemmas
  Std/Tactic/Ext.lean
  test/ext.lean
Labels: awaiting-review

#355 feat: Improve #print prefix filtering.
  Std/Lean/Name.lean
  Std/Lean/Util/EnvSearch.lean
  Std/Tactic/PrintPrefix.lean
  test/print_prefix.lean
Labels: will-merge-soon

#203 feat: more sub lemmas for `Nat`
  Std/Data/Nat/Lemmas.lean
Labels: awaiting-review

#384 feat: add support for not-equals in exists
  Std/Util/ExtendedBinder.lean
Labels: awaiting-review

#383 chore: bump for leanprover/lean4#2904
  Std/Tactic/Lint/Frontend.lean
  lean-toolchain
Labels: awaiting-review, merged-into-nightly-testing, v4.4.0

#398 feat: port List.traverse
  Std/Data/List/Basic.lean
Labels: awaiting-review, will-merge-soon

#386 feat: lemmas characterising Array.all
  Std/Data/Array/Lemmas.lean
Labels: awaiting-review

#403 chore: Consolidate local context extensions.
  Std.lean
  Std/Lean/LocalContext.lean
  Std/Lean/Meta/Basic.lean
  Std/Lean/Meta/LCtx.lean
  Std/Tactic/Simpa.lean
Labels: awaiting-review

#404 chore: Port constName and getAppFnArgs from Mathlib
  Std/Lean/Expr.lean
Labels: awaiting-review

#241 chore: upstream on_goal / pick_goal / swap
  Std.lean
  Std/Tactic/PermuteGoals.lean
  test/on_goal.lean
Labels: will-merge-soon

#388 feat: Array.join
  Std/Data/Array/Basic.lean
  Std/Data/Array/Lemmas.lean
Labels: will-merge-soon

#389 feat: miscellaneous Array lemmas
  Std/Data/Array/Lemmas.lean
  Std/Data/HashMap/WF.lean
  Std/Data/List/Lemmas.lean
Labels: will-merge-soon

#366 Operations for bit representation of `Nat` and `BitVec`.
  Std.lean
  Std/Data/BitVec/Basic.lean
  Std/Data/BitVec/Bitblast.lean
  Std/Data/BitVec/Folds.lean
  Std/Data/BitVec/Lemmas.lean
  Std/Data/Bool.lean
  Std/Data/Fin/Iterate.lean
  Std/Data/Nat/Basic.lean
  Std/Data/Nat/Bitwise.lean
  Std/Data/Nat/Lemmas.lean
  Std/Logic.lean
Labels: will-merge-soon

#409 chore: bump toolchain to v4.3.0
  lean-toolchain
Labels: awaiting-review

#408 fix: DiscrTreeCache.mk init argument should be lazy
  Std/Util/Cache.lean
Labels: awaiting-review
