Repository leanprover-community/batteries, pull requests merged in 2024-05, with the labels that each got.

#772 chore: adaptations for nightly-2024-04-30
  Std/Data/Array/Basic.lean
  Std/Data/Array/Init/Lemmas.lean
  Std/Data/Array/Lemmas.lean
  Std/Data/ByteArray.lean
  Std/Data/Fin/Lemmas.lean
  Std/Data/List/Basic.lean
  Std/Data/List/Init/Lemmas.lean
  Std/Data/List/Lemmas.lean
  Std/Tactic/PrintPrefix.lean
  Std/Util/Cache.lean
  lean-toolchain
  test/congr.lean
  test/print_prefix.lean
Labels: awaiting-review

#755 refactor: move `Function.id_def` from mathlib
  Std/Logic.lean
Labels: awaiting-review

#770 Add `String.length_join` and `List.length_join`
  Std/Data/List/Lemmas.lean
  Std/Data/String/Lemmas.lean
Labels: awaiting-review

#781 chore(Data/List): drop `removeNth`
  Std/Data/List/Basic.lean
  Std/Data/List/Lemmas.lean
Labels: will-merge-soon

#775 chore: add `Union` and `SDiff` instances for `Std.RBSet`
  Std/Data/RBMap/Basic.lean
Labels: awaiting-review

#783 chore: adaptations for nightly-2024-05-06
  Std/Data/Array/Lemmas.lean
  Std/Data/List/Lemmas.lean
  lean-toolchain
Labels: awaiting-review

#785 chore: fix CI for the leanprover -> leanprover-community move
  .github/workflows/merge_conflicts.yml
  .github/workflows/nightly_bump_toolchain.yml
  .github/workflows/nightly_merge_master.yml
Labels: will-merge-soon

#786 chore: deprecations in dot notation
  Batteries/Data/Array/Basic.lean
Labels: awaiting-review, will-merge-soon

#789 doc: fix section titles
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-review

#784 refactor: structurally recursive List.ofFn
  Batteries/Data/List/Basic.lean
Labels: will-merge-soon

#790 refactor: remove `@[simp]` from `List.modifyHead`
  Batteries/Data/List/Basic.lean
Labels: awaiting-review

#791 chore: update `make lint` to use `lake`
  GNUmakefile
Labels: awaiting-review

#792 feat(Data/List/EraseIdx): new file
  Batteries/Data/List.lean
  Batteries/Data/List/EraseIdx.lean
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-review

#750 feat: `Rat.toFloat`
  Batteries/Data/Rat/Basic.lean
  Batteries/Lean/Float.lean
  test/float.lean
Labels: merge-conflict, will-merge-soon

#794 chore: adaptations for nightly-2024-05-11
  Batteries/Data/Array/Basic.lean
  Batteries/Data/Fin/Lemmas.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/WF.lean
  lean-toolchain
  test/list_sublists.lean
Labels: will-merge-soon

#740 feat: RBSet.{upperBound?, lowerBound?} lemmas
  Batteries/Data/RBMap/Basic.lean
  Batteries/Data/RBMap/Lemmas.lean
Labels: awaiting-review, will-merge-soon

#798 chore: silence unreachableTactic test
  test/lint_unreachableTactic.lean
Labels: awaiting-review, will-merge-soon

#797 feat: lake exe test --allow-noisy
  scripts/test.lean
Labels: awaiting-review, will-merge-soon

#802 fix: unused variables
  Batteries/Data/BinomialHeap/Basic.lean
  Batteries/Data/PairingHeap.lean
  Batteries/Data/RBMap/Alter.lean
Labels: awaiting-review

#806 chore: move to v4.8.0-rc2
  lean-toolchain
Labels: awaiting-review, will-merge-soon

#805 chore: update `build.yml` to use `lean-action`
  .github/workflows/build.yml
Labels: awaiting-review

#801 feat: size lemmas for Array.shrink
  Batteries/Data/Array/Lemmas.lean
Labels: awaiting-review

#803 feat: safe Nat indexed Array functions using get_elem_tactic
  Batteries/Data/Array/Basic.lean
Labels: awaiting-review
