Repository leanprover-community/batteries, pull requests merged in 2024-04, with the labels that each got.

#718 chore: golf proof
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#720 doc: add section title
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#712 chore: remove triv tactic
  Std/Tactic/Init.lean
Labels: will-merge-soon

#716 chore: use BEq instead of DecidableEq in List additional ops
  Std/Data/List/Basic.lean
  Std/Data/List/Lemmas.lean
  Std/Data/List/Perm.lean
Labels: will-merge-soon

#725 doc: add examples to `Std.Data.HashMap.Init` docs
  Std/Data/HashMap/Basic.lean
Labels: awaiting-review

#741 fix: for lean4#3851
  Std/Data/Array/Basic.lean
Labels: awaiting-review

#734 feat: `#show_unused` command
  Std.lean
  Std/Tactic/ShowUnused.lean
  test/show_unused.lean
Labels: awaiting-review

#729 chore: remove cross-cutting dep
  Std/Data/Array.lean
  Std/Data/Array/Init/Lemmas.lean
  Std/Data/Array/Lemmas.lean
  Std/Data/Fin/Lemmas.lean
  Std/Data/List.lean
  Std/Data/List/Init/Lemmas.lean
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#735 chore: RBMap.min -> min?
  Std/Data/RBMap/Basic.lean
Labels: awaiting-review

#737 feat: RBNode.reverse
  Std/Classes/Order.lean
  Std/Data/List/Lemmas.lean
  Std/Data/RBMap/Basic.lean
  Std/Data/RBMap/Lemmas.lean
  Std/Data/RBMap/WF.lean
Labels: awaiting-review, depends on another PR

#715 feat: Function.funext_iff and Sum.elim_eq_iff
  Std/Data/Sum/Lemmas.lean
  Std/Logic.lean
Labels: awaiting-review

#714 chore: monadic implementation of classical
  Std/Tactic/Classical.lean
Labels: awaiting-review

#747 feat: List.(take|drop)_set_of_lt
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#736 chore: move theorems RBMap.{Alter -> Lemmas}
  Std/Data/RBMap/Alter.lean
  Std/Data/RBMap/Lemmas.lean
Labels: awaiting-review

#732 chore: add .gitpod.yml and .docker/gitpod/Dockerfile
  .docker/gitpod/Dockerfile
  .gitpod.yml
Labels: awaiting-review

#753 chore: remove upstreamed false_or_by_contra
  Std.lean
  Std/Tactic/FalseOrByContra.lean
  test/false_or_by_contra.lean
Labels: will-merge-soon

#762 chore: cleanup and shorten names in Array.Merge
  Std/Data/Array/Merge.lean
  Std/Lean/Meta/DiscrTree.lean
Labels: awaiting-review

#767 feat(Nat/Gcd): drop an unneeded assumption
  Std/Data/Nat/Gcd.lean
Labels: awaiting-review

#768 feat: add `List.mem_merge`
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#758 fix: don't cast to `Option` in `List.get_zero`
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#769 chore: add `@[simp]` attrs
  Std/Data/List/Count.lean
  Std/Data/List/Lemmas.lean
  Std/Data/List/Pairwise.lean
Labels: awaiting-review

#730 feat: `TransOrd` and `BEqOrd` + instances
  Std/Classes/Order.lean
  Std/Data/Char.lean
  Std/Data/Fin/Lemmas.lean
  Std/Data/List/Lemmas.lean
  Std/Data/String/Lemmas.lean
  Std/Data/UInt.lean
Labels: awaiting-author, merge-conflict, will-merge-soon
