Repository leanprover-community/batteries, pull requests merged in 2024-09, with the labels that each got.

#924 chore: update .gitpod.yml to pre-build Batteries
  .gitpod.yml
Labels: awaiting-review

#916 chore: reduce usage of refine'
  Batteries/Data/Rat/Lemmas.lean
  Batteries/Data/String/Lemmas.lean
Labels: awaiting-review

#902 feat: add `map` and `mapM` for scalar array types
  Batteries.lean
  Batteries/Data/ByteArray.lean
  Batteries/Data/FloatArray.lean
Labels: awaiting-review

#895 feat: lemmas for `Array.insertAt`
  Batteries/Data/Array/Lemmas.lean
Labels: awaiting-review

#888 chore: remove upstreamed code actions
  Batteries/CodeAction/Basic.lean
  Batteries/CodeAction/Deprecated.lean
Labels: awaiting-review

#831 chore: fix some List.modifyNth lemma names
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-review

#807 feat: size lemma for `Array.set!`
  Batteries/Data/Array/Lemmas.lean
Labels: awaiting-review

#897 feat: add `Array.Pairwise`
  Batteries/Data/Array.lean
  Batteries/Data/Array/Pairwise.lean
Labels: awaiting-review

#832 refactor: avoid relying on rfl's behavior on ground terms
  Batteries/Data/Fin/Lemmas.lean
Labels: WIP

#956 feat: compare List.ofFn and Array.ofFn
  Batteries/Data/Array.lean
  Batteries/Data/Array/OfFn.lean
  Batteries/Data/List.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/OfFn.lean
Labels: awaiting-review

#690 feat: fill in proof of Array.data_erase
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-author

#958 feat: automatically test Mathlib against Batteries PRs
  .github/workflows/test_mathlib.yml
Labels: awaiting-review

#967 fix: remove List.erase_of_forall_bne and replace with List.erase_eq_self_iff_forall_bne
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/List/Lemmas.lean
Labels: builds-mathlib

#950 chore: simplify lakefile
  .github/workflows/build.yml
  lakefile.lean
Labels: awaiting-review

#953 feat: decidable quantifiers for `Vector`
  Batteries/Data/Vector/Basic.lean
  Batteries/Data/Vector/Lemmas.lean
  test/vector.lean
Labels: awaiting-author

#970 fix: disable flaky test
  test/MLList.lean
Labels: breaks-mathlib
