Repository leanprover-community/batteries, pull requests merged in 2024-07, with the labels that each got.

#857 chore: deal with nonterminal simps in String/Lemmas
  Batteries/Data/String/Lemmas.lean
Labels: awaiting-review, will-merge-soon

#869 chore: remove 'meta if' from lakefile
  lakefile.lean
Labels: awaiting-review, will-merge-soon

#870 chore: adaptations for nightly-2024-07-01
  Batteries/Data/Array/Basic.lean
  Batteries/Data/List.lean
  Batteries/Data/List/Init/Attach.lean
  Batteries/Data/List/Perm.lean
  Batteries/Data/Range/Lemmas.lean
  lean-toolchain
Labels: awaiting-review, will-merge-soon

#874 chore: remove `proof_wanted` in HashMap.Lemmas
  Batteries/Data/HashMap/Lemmas.lean
Labels: awaiting-review

#868 chore: remove nonterminal simps in UnionFind
  Batteries/Data/UnionFind/Basic.lean
Labels: awaiting-review

#875 chore: add missing since dates to deprecations
  Batteries/Data/Array/Merge.lean
  Batteries/Data/BitVec/Lemmas.lean
  Batteries/Data/Bool.lean
  Batteries/Data/Int/Order.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Count.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Pairwise.lean
  Batteries/Data/Nat/Lemmas.lean
  Batteries/Data/Option/Lemmas.lean
  Batteries/Data/RBMap/Basic.lean
  Batteries/Lean/Delaborator.lean
  Batteries/Logic.lean
  Batteries/StdDeprecations.lean
Labels: awaiting-review

#876 chore: bump toolchain to v4.10.0-rc2
  lean-toolchain
Labels: will-merge-soon

#878 chore: adaptations for nightly-2024-07-10
  Batteries.lean
  Batteries/Classes/BEq.lean
  Batteries/Data/Array/Merge.lean
  Batteries/Data/BitVec/Lemmas.lean
  Batteries/Data/Bool.lean
  Batteries/Data/Char.lean
  Batteries/Data/HashMap/Basic.lean
  Batteries/Data/HashMap/Lemmas.lean
  Batteries/Data/HashMap/WF.lean
  Batteries/Data/Int/Order.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Count.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Pairwise.lean
  Batteries/Data/List/Perm.lean
  Batteries/Data/Nat/Lemmas.lean
  Batteries/Data/Option/Lemmas.lean
  Batteries/Data/RBMap/Basic.lean
  Batteries/Data/RBMap/Lemmas.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/Data/UInt.lean
  Batteries/Data/UnionFind/Basic.lean
  Batteries/Lean/Delaborator.lean
  Batteries/Lean/SMap.lean
  Batteries/Lean/Util/Path.lean
  Batteries/Logic.lean
  Batteries/StdDeprecations.lean
  lean-toolchain
  scripts/runLinter.lean
  test/congr.lean
Labels: awaiting-review, will-merge-soon

#835 chore: upstream most LazyList results from Mathlib
  Batteries/Data/LazyList.lean
Labels: awaiting-review

#879 chore: adaptations for nightly-2024-07-11
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Count.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Pairwise.lean
  Batteries/Data/List/Perm.lean
  lean-toolchain
Labels: awaiting-review, will-merge-soon

#880 doc: fix outdated docstring
  Batteries/Tactic/Lint/Misc.lean
Labels: awaiting-review

#881 feat: allow configuring additional linters to run
  Batteries/Tactic/Lint/Frontend.lean
  scripts/runLinter.lean
Labels: awaiting-review

#871 chore: test file for linting lean4
  test/lint_lean.lean
Labels: awaiting-review, will-merge-soon

#885 chore: adaptations for nightly-2024-07-16
  Batteries/StdDeprecations.lean
  Batteries/Tactic/Lint/Basic.lean
  lean-toolchain
Labels: awaiting-review

#877 feat: Array lemma for empty map added
  Batteries/Data/Array/Lemmas.lean
Labels: awaiting-review

#884 chore: deprecate LazyList
  Batteries/Data/LazyList.lean
Labels: awaiting-review, will-merge-soon

#892 chore: robustify for byAsSorry
  Batteries/CodeAction/Deprecated.lean
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-review

#893 chore: adaptations for nightly-2024-07-26
  Batteries.lean
  Batteries/Data/HashMap/WF.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Count.lean
  Batteries/Data/List/EraseIdx.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Perm.lean
  Batteries/Data/Nat/Basic.lean
  Batteries/Data/Nat/Lemmas.lean
  Batteries/Util/CheckTactic.lean
  lean-toolchain
  test/array.lean
Labels: awaiting-review

#896 chore: adaptations for nightly-2024-07-29
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Count.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Pairwise.lean
  Batteries/Data/String/Lemmas.lean
  lean-toolchain
Labels: awaiting-review

#891 feat: some array lemma aliases
  Batteries/Data/Array/Lemmas.lean
Labels: awaiting-review

#898 chore: adaptations for nightly-2024-07-30
  Batteries/Data/List/Lemmas.lean
  lean-toolchain
Labels: awaiting-review, will-merge-soon

#894 chore: backports for leanprover/lean4#4814
  Batteries/Classes/Order.lean
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-review, will-merge-soon
