Repository leanprover-community/batteries, pull requests merged in 2024-03, with the labels that each got.

#678 chore: adaptations for nightly-2024-03-01
  Std.lean
  Std/Data/Array/Lemmas.lean
  Std/Data/HashMap/WF.lean
  Std/Data/Int/DivMod.lean
  Std/Data/Int/Order.lean
  Std/Data/List/Basic.lean
  Std/Data/List/Lemmas.lean
  Std/Tactic/Basic.lean
  Std/Tactic/ShowTerm.lean
  lean-toolchain
  test/add_suggestion.lean
  test/bitvec.lean
  test/bitvec_simproc.lean
  test/change.lean
  test/coe.lean
  test/decidability.lean
  test/ext.lean
  test/guard_msgs.lean
  test/guardexpr.lean
  test/int.lean
  test/json.lean
  test/left_right.lean
  test/library_search/basic.lean
  test/norm_cast.lean
  test/omega/benchmark.lean
  test/omega/examples.lean
  test/omega/test.lean
  test/rcases.lean
  test/repeat.lean
  test/replace.lean
  test/run_cmd.lean
  test/show_term.lean
  test/simpa.lean
  test/solve_by_elim.lean
  test/symm.lean
Labels: awaiting-review

#579 feat: `List.merge` and lemmas
  Std/Data/List/Basic.lean
  Std/Data/List/Lemmas.lean
  Std/Data/List/Perm.lean
Labels: awaiting-review

#676 docs: add further build info
  README.md
Labels: awaiting-review

#696 chore: don't use SatisfiesM in proving statements about pure functions
  Std/Classes/SatisfiesM.lean
  Std/Data/Array.lean
  Std/Data/Array/Lemmas.lean
  Std/Data/Array/Monadic.lean
  Std/Data/HashMap/Basic.lean
Labels: awaiting-review

#698 style: indent subsequent theorem statement
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#688 feat: add more theorems about `Array.swap`'s basic properties
  Std/Data/Array/Lemmas.lean
Labels: awaiting-review

#489 feat: implement union-find
  Std.lean
  Std/Data/Array/Lemmas.lean
  Std/Data/UnionFind/Basic.lean
  Std/Data/UnionFind/Lemmas.lean
Labels: awaiting-review

#272 De-mathlib `List.take` and `List.drop` lemmas
  Std/Data/List/Lemmas.lean
  Std/Data/List/Pairwise.lean
  Std/Data/String/Lemmas.lean
Labels: awaiting-review

#528 feat: correctness for `Fin.foldl` and `Fin.foldr`
  Std/Data/Fin/Basic.lean
  Std/Data/Fin/Lemmas.lean
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#702 chore: remove upstreamed `rfl` macro rules
  Std/Tactic/Init.lean
Labels: awaiting-review

#707 chore: update CI actions which are triggering warnings
  .github/workflows/build.yml
  .github/workflows/nightly_bump_toolchain.yml
  .github/workflows/nightly_detect_failure.yml
  .github/workflows/nightly_merge_master.yml
Labels: awaiting-review

#713 chore: remove some already upstreamed tactics
  Std/Tactic/Init.lean
Labels: awaiting-review

#710 feat: better `List.take_drop` and `List.drop_take`
  Std/Data/List/Lemmas.lean
Labels: awaiting-review

#701 chore: removed unnecessary array indexing proofs
  Std/CodeAction/Deprecated.lean
  Std/Data/Array/Lemmas.lean
  Std/Data/Array/Monadic.lean
  Std/Data/HashMap/WF.lean
  Std/Lean/Meta/AssertHypotheses.lean
  Std/Linter/UnnecessarySeqFocus.lean
Labels: will-merge-soon

#687 feat: add Decidable instance for List.Forall₂
  Std/Data/List/Basic.lean
Labels: awaiting-review, will-merge-soon
