Repository leanprover-community/batteries, pull requests merged in 2024-11, with the labels that each got.

#1020 chore: adaptations for nightly-2024-10-18 thru 2024-10-30
  Batteries/Data/Array/Basic.lean
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/Array/Match.lean
  Batteries/Data/Array/Monadic.lean
  Batteries/Data/ByteArray.lean
  Batteries/Data/HashMap/Basic.lean
  Batteries/Data/HashMap/WF.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/Nat/Lemmas.lean
  Batteries/Data/UnionFind/Basic.lean
  Batteries/Data/UnionFind/Lemmas.lean
  Batteries/Data/Vector/Basic.lean
  Batteries/Data/Vector/Lemmas.lean
  Batteries/Tactic/Alias.lean
  Batteries/Tactic/HelpCmd.lean
  lean-toolchain
  test/array.lean
  test/case.lean
  test/congr.lean
  test/print_prefix.lean
  test/simpa.lean
Labels: will-merge-soon

#1022 chore: adaptations for nightly-2024-11-01
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/AssocList.lean
  Batteries/Data/Range/Lemmas.lean
  Batteries/Tactic/PrintPrefix.lean
  lean-toolchain
  test/print_prefix.lean
  test/vector.lean
Labels: will-merge-soon

#985 feat: add `drop` and `take` for streams
  Batteries.lean
  Batteries/Data/Stream.lean
Labels: awaiting-review, builds-mathlib

#1024 chore: turn batteries tests into a library
  .github/workflows/build.yml
  Batteries.lean
  BatteriesTest/Internal/DummyLabelAttr.lean
  BatteriesTest/Internal/DummyLibraryNote.lean
  BatteriesTest/Internal/DummyLibraryNote2.lean
  BatteriesTest/MLList.lean
  BatteriesTest/absurd.lean
  BatteriesTest/alias.lean
  BatteriesTest/array.lean
  BatteriesTest/by_contra.lean
  BatteriesTest/case.lean
  BatteriesTest/congr.lean
  BatteriesTest/conv_equals.lean
  BatteriesTest/exfalso.lean
  BatteriesTest/float.lean
  BatteriesTest/help_cmd.lean
  BatteriesTest/import_lean.lean
  BatteriesTest/instances.lean
  BatteriesTest/isIndependentOf.lean
  BatteriesTest/kmp_matcher.lean
  BatteriesTest/lemma_cmd.lean
  BatteriesTest/library_note.lean
  BatteriesTest/lintTC.lean
  BatteriesTest/lint_docBlame.lean
  BatteriesTest/lint_docBlameThm.lean
  BatteriesTest/lint_dupNamespace.lean
  BatteriesTest/lint_empty.lean
  BatteriesTest/lint_lean.lean
  BatteriesTest/lint_simpNF.lean
  BatteriesTest/lint_unreachableTactic.lean
  BatteriesTest/lintsimp.lean
  BatteriesTest/lintunused.lean
  BatteriesTest/list_sublists.lean
  BatteriesTest/nondet.lean
  BatteriesTest/norm_cast.lean
  BatteriesTest/omega/benchmark.lean
  BatteriesTest/on_goal.lean
  BatteriesTest/print_prefix.lean
  BatteriesTest/proof_wanted.lean
  BatteriesTest/register_label_attr.lean
  BatteriesTest/rfl.lean
  BatteriesTest/seq_focus.lean
  BatteriesTest/show_term.lean
  BatteriesTest/show_unused.lean
  BatteriesTest/simp_trace.lean
  BatteriesTest/simpa.lean
  BatteriesTest/solve_by_elim.lean
  BatteriesTest/trans.lean
  BatteriesTest/tryThis.lean
  BatteriesTest/vector.lean
  BatteriesTest/where.lean
  lakefile.toml
Labels: awaiting-review, builds-mathlib

#1025 refactor: cleanup `Vector` API
  Batteries/Data/Vector/Basic.lean
  Batteries/Data/Vector/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1030 feat: improve induction code action
  Batteries/CodeAction/Misc.lean
Labels: awaiting-review, builds-mathlib

#1031 chore: update README with new lakefile syntax
  README.md
Labels: awaiting-review, will-merge-soon, builds-mathlib

#1033 chore: add unlabeled PR workflow
  .github/workflows/labels-from-status.yml
Labels: awaiting-review, builds-mathlib

#811 feat: detect default target on runLinter
  scripts/runLinter.lean
Labels: awaiting-review, builds-mathlib

#850 refactor: implement `BinaryHeap` using `Vector`
  Batteries/Data/BinaryHeap.lean
Labels: awaiting-review, builds-mathlib

#1036 perf: inline the `Decidable (Coprime _ _)` instance
  Batteries/Data/Nat/Gcd.lean
Labels: awaiting-review, builds-mathlib

#1038 chore: robustify some String proofs
  Batteries/Data/String/Lemmas.lean
Labels: awaiting-review, will-merge-soon, builds-mathlib

#1028 feat: generate docs from subdirectory
  .github/workflows/docs-deploy.yml
  .github/workflows/docs-release.yml
  README.md
  docs/README.md
  docs/lake-manifest.json
  docs/lakefile.toml
Labels: awaiting-review, builds-mathlib

#1034 feat: List.SatisfiesM_foldlM
  Batteries/Data/List.lean
  Batteries/Data/List/Monadic.lean
Labels: builds-mathlib

#1039 chore: cleanup proof of satisfiesM_foldlM
  Batteries/Data/List/Monadic.lean
Labels: awaiting-review

#1029 feat: sugar for SatisfiesM
  Batteries.lean
  Batteries/Classes/SatisfiesM.lean
  Batteries/Data/HashMap/Basic.lean
  Batteries/Lean/EStateM.lean
  Batteries/Lean/Except.lean
  Batteries/Lean/LawfulMonad.lean
  Batteries/Lean/SatisfiesM.lean
  BatteriesTest/satisfying.lean
Labels: builds-mathlib

#1042 chore: remove unnecessary import in Batteries.Lean.LawfulMonad
  Batteries/Lean/LawfulMonad.lean
Labels: awaiting-review

#1043 chore: remove duplicate NameMap forIn instance
  Batteries/Lean/NameMap.lean
Labels: awaiting-review

#1045 chore: update authors lines
  Batteries/Control/Nondet/Basic.lean
  Batteries/Data/HashMap/Lemmas.lean
  Batteries/Data/MLList/Basic.lean
  Batteries/Data/MLList/Heartbeats.lean
  Batteries/Data/MLList/IO.lean
  Batteries/Lean/Except.lean
  Batteries/Lean/IO/Process.lean
  Batteries/Lean/Meta/DiscrTree.lean
  Batteries/Lean/Meta/Simp.lean
  Batteries/Lean/System/IO.lean
  BatteriesTest/Internal/DummyLabelAttr.lean
  BatteriesTest/omega/benchmark.lean
  BatteriesTest/show_term.lean
  BatteriesTest/solve_by_elim.lean
Labels: awaiting-review

#1044 chore: remove >6 month old deprecations
  Batteries.lean
  Batteries/Data/Array/Merge.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/RBMap/Basic.lean
  Batteries/Lean/Delaborator.lean
  Batteries/Lean/HashSet.lean
  Batteries/Logic.lean
  Batteries/StdDeprecations.lean
Labels: awaiting-review, will-merge-soon, breaks-mathlib

#1040 chore: adaptations for nightly-2024-11-12
  Batteries/Data/Array/Basic.lean
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/Array/Merge.lean
  Batteries/Data/Array/Monadic.lean
  Batteries/Data/Array/OfFn.lean
  Batteries/Data/Array/Pairwise.lean
  Batteries/Data/BinaryHeap.lean
  Batteries/Data/ByteArray.lean
  Batteries/Data/Fin/Basic.lean
  Batteries/Data/Fin/Lemmas.lean
  Batteries/Data/HashMap/Basic.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/OfFn.lean
  Batteries/Data/MLList/Basic.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/Data/UnionFind/Basic.lean
  Batteries/Data/UnionFind/Lemmas.lean
  Batteries/Data/Vector/Basic.lean
  BatteriesTest/array.lean
  lean-toolchain
Labels: will-merge-soon

#1046 chore: deprecate Expr.forallArity, per todo
  Batteries/Lean/Expr.lean
Labels: awaiting-review, will-merge-soon, breaks-mathlib

#1048 chore: adaptations for nightly-2024-11-13
  Batteries/Lean/Meta/Simp.lean
  Batteries/Tactic/Lint/Simp.lean
  lean-toolchain
Labels: will-merge-soon

#1050 fix: use two tokens for open private/export private
  Batteries/Tactic/OpenPrivate.lean
  BatteriesTest/OpenPrivateDefs.lean
  BatteriesTest/openPrivate.lean
Labels: awaiting-author, builds-mathlib

#1049 chore: adaptations for nightly-2024-11-14
  Batteries.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/UnionFind/Basic.lean
  Batteries/Lean/NameMap.lean
  lean-toolchain
Labels: will-merge-soon

#1054 chore: remove @[simp] attributes from monad-specific SatisfiesM lemmas
  Batteries/Classes/SatisfiesM.lean
Labels: awaiting-review, builds-mathlib

#1057 chore: cleanup breaking non-terminal simps
  Batteries/Data/Range/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1056 fix: Readme.md needs "git" token in lakefile.lean
  README.md
Labels: awaiting-review

#1059 chore: fix workflow token
  .github/workflows/labels-from-status.yml
Labels: awaiting-review

#1061 chore: fix two deprecations
  Batteries/Lean/Expr.lean
Labels: awaiting-review

#1062 feat: more vector lemmas
  Batteries/Data/Vector/Basic.lean
  Batteries/Data/Vector/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1065 feat: add KMP frontend for lists
  Batteries/Data/List.lean
  Batteries/Data/List/Matcher.lean
  BatteriesTest/kmp_matcher.lean
Labels: awaiting-review, builds-mathlib

#1055 refactor: add List.finRange and Array.finRange
  Batteries/Data/Array/Basic.lean
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/Fin.lean
  Batteries/Data/Fin/Basic.lean
  Batteries/Data/Fin/Fold.lean
  Batteries/Data/Fin/Lemmas.lean
  Batteries/Data/List.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/FinRange.lean
Labels: awaiting-review, builds-mathlib

#1066 feat: List.dropPrefix? / dropSuffix? / dropInfix? and specification lemmas
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1068 chore: bump toolchain to v4.14.0-rc3
  lean-toolchain
Labels: awaiting-review

#1069 chore: update docs-release action
  .github/workflows/docs-release.yml
Labels: awaiting-review
