Repository leanprover-community/batteries, pull requests merged in 2024-10, with the labels that each got.

#971 chore: adaptations for nightly-2024-09-27
  Batteries/Classes/SatisfiesM.lean
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/Array/OfFn.lean
  Batteries/Data/Array/Pairwise.lean
  Batteries/Data/Fin/Lemmas.lean
  Batteries/Data/HashMap/WF.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/Vector/Basic.lean
  Batteries/Lean/HashSet.lean
  lean-toolchain
  test/lint_lean.lean
Labels: will-merge-soon

#974 chore: cleanup some unused arguments
  Batteries/Classes/SatisfiesM.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/RBMap/Alter.lean
  Batteries/Logic.lean
  Batteries/WF.lean
Labels: awaiting-review, builds-mathlib

#975 fix: argument order and make abbrev
  Batteries/Data/Array/Basic.lean
Labels: awaiting-review, builds-mathlib

#976 chore: adaptations for nightly-2024-10-01
  Batteries/Data/Array/Basic.lean
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/Array/Pairwise.lean
  Batteries/Data/ByteArray.lean
  Batteries/Data/HashMap/WF.lean
  Batteries/Data/UnionFind/Basic.lean
  lean-toolchain
Labels: will-merge-soon, breaks-mathlib

#978 chore: adaptations for nightly-2024-10-03
  Batteries.lean
  Batteries/Lean/HashSet.lean
  Batteries/Lean/Meta/AssertHypotheses.lean
  Batteries/Lean/Meta/Clear.lean
  lean-toolchain
Labels: will-merge-soon

#972 feat: `l <+~ [] ↔ l = []`
  Batteries/Data/List/Perm.lean
Labels: awaiting-author

#890 feat: add bisection algorithm
  Batteries/Data/Nat.lean
  Batteries/Data/Nat/Bisect.lean
Labels: awaiting-review, builds-mathlib

#814 feat: `Fin.foldlM` and `Fin.foldrM`
  Batteries/Data/Fin/Basic.lean
  Batteries/Data/Fin/Lemmas.lean
Labels: awaiting-review, merge-conflict, builds-mathlib

#986 chore: remove duplicate theorem about lists
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-review

#983 chore: move panicWith out of UnionFind
  Batteries.lean
  Batteries/Data/UnionFind/Basic.lean
  Batteries/Util/Panic.lean
Labels: awaiting-review

#990 feat: characterize `OfScientific.ofScientific` on `Rat`
  Batteries/Data/Rat/Basic.lean
  Batteries/Data/Rat/Lemmas.lean
Labels: awaiting-review

#989 feat: upstream DList results from Mathlib
  Batteries/Data/DList.lean
  Batteries/Data/DList/Basic.lean
  Batteries/Data/DList/Lemmas.lean
  Batteries/StdDeprecations.lean
Labels: awaiting-review

#988 feat: add `Array.eraseIdx!` and some lemmas
  Batteries/Data/Array/Basic.lean
  Batteries/Data/Array/Lemmas.lean
Labels: awaiting-review

#991 chore: cleanup of DList api
  Batteries/Data/DList/Basic.lean
  Batteries/Data/DList/Lemmas.lean
Labels: awaiting-review

#969 feat: add `#help` commands
  Batteries.lean
  Batteries/Tactic/HelpCmd.lean
  test/help_cmd.lean
Labels: awaiting-review, builds-mathlib

#997 fix: make `proof_wanted` not report unused variables
  Batteries/Util/ProofWanted.lean
  test/proof_wanted.lean
Labels: awaiting-review

#992 chore: deprecate `Expr.lambdaArity` in favor of existing upstream version
  Batteries/Lean/Expr.lean
Labels: awaiting-review, builds-mathlib

#996 fix: print prefix bug
  Batteries/Tactic/PrintPrefix.lean
  test/print_prefix.lean
Labels: awaiting-review, builds-mathlib

#1001 feat: add `trans` tactic
  Batteries.lean
  Batteries/Tactic/Trans.lean
  test/trans.lean
Labels: awaiting-review, builds-mathlib

#1003 chore: rename List.modifyNth->modify and insertNth->insertIdx
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Perm.lean
Labels: breaks-mathlib

#1005 chore: switch to lakefile.toml
  lakefile.lean
  lakefile.toml
Labels: builds-mathlib

#948 feat: add `#help note` command
  Batteries.lean
  Batteries/Tactic/HelpCmd.lean
  Batteries/Test/Internal/DummyLibraryNote.lean
  Batteries/Test/Internal/DummyLibraryNote2.lean
  Batteries/Util/LibraryNote.lean
  test/library_note.lean
Labels: awaiting-review, builds-mathlib

#1008 feat: use gh command to get pull request info
  .github/workflows/test_mathlib.yml
Labels: builds-mathlib

#1018 feat: fill some gaps in Vector lemmas
  Batteries/Data/Vector/Lemmas.lean
Labels: builds-mathlib
