Repository leanprover-community/batteries, pull requests merged in 2024-02, with the labels that each got.

#574 chore: bump to v4.5.0
  lean-toolchain
Labels: awaiting-review

#568 chore: remove Std.Data.List import from Omega
  Std/Data/List.lean
  Std/Data/List/Basic.lean
  Std/Data/List/Init/Basic.lean
  Std/Data/List/Init/Lemmas.lean
  Std/Data/List/Lemmas.lean
  Std/Tactic/Omega/IntList.lean
  Std/Tactic/Omega/LinearCombo.lean
  Std/Tactic/Omega/MinNatAbs.lean
Labels: will-merge-soon

#571 chore: fixes for `simp` refactor
  Std/Data/List.lean
  Std/Data/List/Basic.lean
  Std/Data/List/Init/Basic.lean
  Std/Data/List/Init/Lemmas.lean
  Std/Data/List/Lemmas.lean
  Std/Lean/Meta/Simp.lean
  Std/Tactic/Lint/Simp.lean
  Std/Tactic/NormCast.lean
  Std/Tactic/Omega/IntList.lean
  Std/Tactic/Omega/LinearCombo.lean
  Std/Tactic/Omega/MinNatAbs.lean
  lean-toolchain
Labels: awaiting-review, v4.6.0

#558 feat: lemmas for BitVec
  Std/Data/BitVec/Basic.lean
  Std/Data/BitVec/Lemmas.lean
  Std/Data/Fin/Lemmas.lean
  Std/Data/Nat/Bitwise.lean
Labels: will-merge-soon

#570 fix: revert OmegaM state when not multiplying out
  Std/Tactic/Omega/Frontend.lean
  Std/Tactic/Omega/OmegaM.lean
  test/omega/test.lean
Labels: will-merge-soon

#576 chore: move to v4.6.0-rc1, merging adaptations
  Std/CodeAction/Basic.lean
  Std/Data/Array/Init/Basic.lean
  Std/Data/Array/Init/Lemmas.lean
  Std/Data/Array/Lemmas.lean
  Std/Data/Array/Match.lean
  Std/Data/Array/Merge.lean
  Std/Data/BinomialHeap/Basic.lean
  Std/Data/ByteArray.lean
  Std/Data/Fin/Basic.lean
  Std/Data/Fin/Iterate.lean
  Std/Data/Fin/Lemmas.lean
  Std/Data/HashMap/Basic.lean
  Std/Data/HashMap/WF.lean
  Std/Data/Nat/Basic.lean
  Std/Data/PairingHeap.lean
  Std/Data/RBMap/Basic.lean
  Std/Data/RBMap/WF.lean
  Std/Data/String/Basic.lean
  Std/Lean/Delaborator.lean
  Std/Lean/InfoTree.lean
  Std/Lean/Meta/Basic.lean
  Std/Lean/Meta/DiscrTree.lean
  Std/Lean/Meta/LazyDiscrTree.lean
  Std/Lean/Meta/Simp.lean
  Std/Tactic/Ext/Attr.lean
  Std/Tactic/LibrarySearch.lean
  Std/Tactic/Lint/Misc.lean
  Std/Tactic/Lint/Simp.lean
  Std/Tactic/NormCast.lean
  Std/Tactic/Omega/OmegaM.lean
  Std/Tactic/RCases.lean
  Std/Tactic/Relation/Rfl.lean
  Std/Tactic/Relation/Symm.lean
  Std/Tactic/SimpTrace.lean
  Std/Tactic/Simpa.lean
  Std/Tactic/SqueezeScope.lean
  Std/Util/Cache.lean
  Std/WF.lean
  lean-toolchain
  test/rcases.lean
Labels: awaiting-review

#575 feat: omega handles min, max, if
  Std/Tactic/Omega/Config.lean
  Std/Tactic/Omega/Frontend.lean
  Std/Tactic/Omega/Int.lean
  Std/Tactic/Omega/OmegaM.lean
  test/omega/test.lean
Labels: will-merge-soon

#578 fix: omega uses local values
  Std/Tactic/Omega/Core.lean
  Std/Tactic/Omega/Frontend.lean
  Std/Tactic/Omega/OmegaM.lean
  test/omega/test.lean
Labels: will-merge-soon

#584 feat: reduce assumptions from `size_swap!`
  Std/Data/Array/Lemmas.lean
Labels: will-merge-soon

#581 feat: simprocs for `BitVec` literals
  Std/Data/BitVec.lean
  Std/Data/BitVec/Basic.lean
  Std/Data/BitVec/Lemmas.lean
  Std/Data/BitVec/Simprocs.lean
  lean-toolchain
  scripts/nolints.json
  test/bitvec_simproc.lean
Labels: awaiting-review

#587 chore: retain history of omega benchmarks
  test/omega/benchmark.lean
Labels: awaiting-review

#592 chore: upstream decidability instances for bounded Nats
  Std/Data/Nat/Lemmas.lean
  test/decidability.lean
Labels: awaiting-review

#588 feat: omega uses Lean.HashMap instead of Std.Data.HashMap
  Std/Tactic/Omega/Coeffs/IntList.lean
  Std/Tactic/Omega/Core.lean
  test/omega/benchmark.lean
Labels: awaiting-review, depends on another PR

#595 chore: add missing copyright headers
  Std/Data/BitVec/Folds.lean
  Std/Data/BitVec/Lemmas.lean
  Std/Data/Range/Lemmas.lean
  Std/Data/Rat/Lemmas.lean
  Std/Data/UInt.lean
  Std/Tactic/Omega.lean
  Std/Tactic/Omega/Coeffs/IntList.lean
  Std/Test/Internal/DummyLabelAttr.lean
Labels: awaiting-review

#594 chore: make Std.Tactic.Basic an import only
  Std.lean
  Std/Data/Nat/Lemmas.lean
  Std/Tactic/Basic.lean
  Std/Tactic/Ext.lean
  Std/Tactic/Init.lean
Labels: awaiting-review, will-merge-soon

#602 chore: remove imports of Std.Tactic.Basic
  Std/Data/Array/Init/Lemmas.lean
  Std/Data/Array/Lemmas.lean
  Std/Data/Int/Order.lean
  Std/Data/Nat/Bitwise.lean
  Std/Data/RBMap/WF.lean
  Std/Data/Range/Lemmas.lean
  Std/Data/Rat/Lemmas.lean
  Std/Data/String/Lemmas.lean
  Std/Lean/Meta/LazyDiscrTree.lean
  Std/Logic.lean
  Std/Tactic/Congr.lean
  Std/Tactic/LibrarySearch.lean
  Std/Tactic/SolveByElim.lean
  test/on_goal.lean
Labels: awaiting-review

#606 chore: don't use ext in omega
  Std/Tactic/Omega/LinearCombo.lean
Labels: awaiting-review, will-merge-soon

#608 chore: classical logic lemmas needed for push_neg
  Std/Logic.lean
  Std/Tactic/Omega/MinNatAbs.lean
Labels: will-merge-soon

#609 chore: fix Nat.pow_two_pos -> Nat.two_pow_pos
  Std/Data/BitVec/Basic.lean
  Std/Data/BitVec/Bitblast.lean
  Std/Data/BitVec/Lemmas.lean
  Std/Data/Nat/Bitwise.lean
  Std/Data/Nat/Init/Lemmas.lean
  Std/Data/UInt.lean
Labels: will-merge-soon

#620 chore: remove omega dependence on norm_cast
  Std/Tactic/Omega/Constraint.lean
Labels: awaiting-review

#596 feat: more BitVec lemmas
  Std/Data/BitVec/Basic.lean
  Std/Data/BitVec/Lemmas.lean
  Std/Data/Fin/Lemmas.lean
  Std/Data/Nat/Bitwise.lean
  Std/Data/Nat/Lemmas.lean
Labels: awaiting-review, will-merge-soon

#621 feat: omega only replaces mod with div when the modulus is a literal
  Std/Tactic/Omega/Frontend.lean
  Std/Tactic/Omega/Int.lean
  Std/Tactic/Omega/OmegaM.lean
  test/omega/test.lean
Labels: awaiting-review

#607 chore: upstream Fin.coe_sub_iff_le from Mathlib
  Std/Data/Fin/Lemmas.lean
Labels: will-merge-soon

#628 chore: upstream pow_dvd_pow_iff_pow_le_pow
  Std/Data/BitVec/Lemmas.lean
  Std/Data/Nat/Lemmas.lean
Labels: will-merge-soon

#624 chore: upstream some Nat lemmas/simp attributes
  Std/Data/BitVec/Lemmas.lean
  Std/Data/Nat/Lemmas.lean
Labels: awaiting-review, will-merge-soon

#610 chore: split Int/Order and Int/DivMod
  Std/Data/Int.lean
  Std/Data/Int/DivMod.lean
  Std/Data/Int/Init/DivMod.lean
  Std/Data/Int/Init/Lemmas.lean
  Std/Data/Int/Init/Order.lean
  Std/Data/Int/Order.lean
  Std/Data/Rat/Lemmas.lean
  Std/Tactic/Omega/Frontend.lean
  Std/Tactic/Omega/Int.lean
  Std/Tactic/Omega/IntList.lean
  Std/Tactic/Omega/MinNatAbs.lean
Labels: awaiting-review, will-merge-soon

#622 chore: further cleanup of proofs in BitVec.BitBlast
  Std/Data/BitVec/Bitblast.lean
Labels: will-merge-soon

#623 chore: adaptations for nightly-2024-02-12
  Std.lean
  Std/Tactic/GuardExpr.lean
  Std/Tactic/Init.lean
  lean-toolchain
  test/bitvec.lean
  test/case.lean
  test/change.lean
  test/classical.lean
  test/congr.lean
  test/conv_equals.lean
  test/false_or_by_contra.lean
  test/float.lean
  test/guardexpr.lean
  test/int.lean
  test/on_goal.lean
  test/rcases.lean
Labels: awaiting-review, will-merge-soon

#632 chore: adaptations for nightly-2024-02-13
  Std.lean
  Std/Data/Int/DivMod.lean
  Std/Data/Int/Init/DivMod.lean
  Std/Data/List/Lemmas.lean
  Std/Lean/Command.lean
  Std/Lean/Meta/DiscrTree.lean
  Std/Linter/UnnecessarySeqFocus.lean
  Std/Linter/UnreachableTactic.lean
  Std/Tactic/Change.lean
  Std/Tactic/Ext.lean
  Std/Tactic/Ext/Attr.lean
  lean-toolchain
  test/change.lean
Labels: will-merge-soon

#631 feat: lemmas about Nat.pow
  Std/Data/Nat/Bitwise.lean
  Std/Data/Nat/Lemmas.lean
Labels: will-merge-soon

#634 feat: prove `allOnes _ - x = ~~~x`
  Std/Data/BitVec/Bitblast.lean
  Std/Data/BitVec/Lemmas.lean
Labels: will-merge-soon

#637 feat: lemmas about `BitVec.getLsb` and bitwise ops (and/or/xor)
  Std/Data/BitVec/Lemmas.lean
Labels: awaiting-review

#641 refactor: improve consistency of BitVec lemmas
  Std/Data/BitVec/Lemmas.lean
Labels: awaiting-review

#630 chore: upstream LazyList from Mathlib
  Std.lean
  Std/Data/LazyList.lean
Labels: will-merge-soon

#643 chore: Drop Std.Data.Nat.Lemmas from Omega dependencies.
  Std/Data/Int/Init/DivMod.lean
  Std/Data/Int/Init/Lemmas.lean
  Std/Data/Int/Order.lean
  Std/Data/List/Basic.lean
  Std/Data/Nat.lean
  Std/Data/Nat/Basic.lean
  Std/Data/Nat/Gcd.lean
  Std/Data/Nat/Init/Basic.lean
  Std/Data/Nat/Init/Dvd.lean
  Std/Data/Nat/Init/Gcd.lean
  Std/Data/Nat/Init/Lemmas.lean
  Std/Data/Nat/Lemmas.lean
  Std/Tactic/Omega/Constraint.lean
  Std/Tactic/Omega/IntList.lean
  Std/Tactic/Omega/MinNatAbs.lean
Labels: will-merge-soon

#642 chore: exact? can't use constructor; too slow
  Std/Tactic/LibrarySearch.lean
  test/library_search/basic.lean
Labels: awaiting-review, will-merge-soon

#639 feat: ofbool_eq_iff_eq
  Std/Data/BitVec/Lemmas.lean
Labels: awaiting-review

#619 chore: change unsafe to partial in DiscrTree
  Std/Lean/Meta/DiscrTree.lean
  Std/Tactic/Ext/Attr.lean
Labels: awaiting-review, will-merge-soon

#617 feat: add `Rat.mk_den_one` simp lemma
  Std/Data/Rat/Lemmas.lean
Labels: will-merge-soon

#653 chore: simplify the proof of `BitVec.eq_of_toFin_eq`
  Std/Data/BitVec/Lemmas.lean
Labels: awaiting-review

#651 Rat: remove `ext` attribute
  Std/Data/Rat/Basic.lean
  Std/Data/Rat/Lemmas.lean
Labels: will-merge-soon

#645 feat: ∀(x : BitVec w.succ), msb x = 1 iff x >= 2^w
  Std/Data/BitVec/Lemmas.lean
Labels: will-merge-soon

#544 feat: `HashMap.empty_find?` + helper lemmas
  Std/Data/Array/Lemmas.lean
  Std/Data/HashMap/Lemmas.lean
Labels: awaiting-author

#655 feat: `BitVec.toFin_not` lemma
  Std/Data/BitVec/Lemmas.lean
Labels: awaiting-review

#648 feat: add toFin_shiftLeft
  Std/Data/BitVec/Lemmas.lean
Labels: awaiting-review

#659 feat: `BitVec.toFin_ofNat` lemma
  Std/Data/BitVec/Lemmas.lean
Labels: awaiting-review

#658 feat: simp-lemmas about `BitVec.cast`
  Std/Data/BitVec/Lemmas.lean
Labels: will-merge-soon

#638 chore: lemma for BitVec.ofFin to .ofNat
  Std/Data/BitVec/Lemmas.lean
  test/bitvec.lean
Labels: will-merge-soon

#647 feat: Add a simp lemma `Nat.cast x = BitVec.ofNat _ x`
  Std/Data/BitVec/Basic.lean
Labels: will-merge-soon

#660 feat: establish `BitVec.allOnes` as simp normal form
  Std/Data/BitVec/Lemmas.lean
Labels: will-merge-soon

#654 chore: refactor Backtrack and SolveByElim to remove Nondet dependency
  Std.lean
  Std/Lean/Meta/Iterator.lean
  Std/Tactic/SolveByElim.lean
  Std/Tactic/SolveByElim/Backtrack.lean
Labels: will-merge-soon

#542 feat: restore lemmas about order and Int.ediv
  Std/Data/Int/DivMod.lean
  Std/Data/Int/Order.lean
Labels: awaiting-review, merge-conflict

#667 feat: Introduce `#check_simp !~>` to check a term is in normal form.
  Std/Util/CheckTactic.lean
  test/array.lean
Labels: awaiting-review

#668 chore: adaptations for nightly-2024-02-22
  Std.lean
  Std/Classes/Order.lean
  Std/Classes/SetNotation.lean
  Std/Data/Array/Lemmas.lean
  Std/Data/BitVec.lean
  Std/Data/BitVec/Basic.lean
  Std/Data/BitVec/Bitblast.lean
  Std/Data/BitVec/Folds.lean
  Std/Data/BitVec/Lemmas.lean
  Std/Data/BitVec/Simprocs.lean
  Std/Data/Fin/Lemmas.lean
  Std/Data/Int/Gcd.lean
  Std/Data/List/Basic.lean
  Std/Data/List/Lemmas.lean
  Std/Data/Nat.lean
  Std/Data/Nat/Basic.lean
  Std/Data/Nat/Bitwise.lean
  Std/Data/Rat/Lemmas.lean
  Std/Data/String/Lemmas.lean
  Std/Data/Sum/Basic.lean
  Std/Lean/Meta/Basic.lean
  Std/Lean/Meta/Iterator.lean
  Std/Lean/Parser.lean
  Std/Tactic/Basic.lean
  Std/Tactic/LabelAttr.lean
  Std/Tactic/LibrarySearch.lean
  Std/Tactic/NormCast.lean
  Std/Tactic/NormCast/Ext.lean
  Std/Tactic/NormCast/Lemmas.lean
  Std/Tactic/Relation/Symm.lean
  Std/Tactic/SimpTrace.lean
  Std/Tactic/Simpa.lean
  Std/Tactic/SolveByElim.lean
  Std/Tactic/SolveByElim/Backtrack.lean
  Std/Tactic/SqueezeScope.lean
  Std/Test/Internal/DummyLabelAttr.lean
  Std/Util/CheckTactic.lean
  lean-toolchain
  test/array.lean
  test/ext.lean
  test/isIndependentOf.lean
  test/norm_cast.lean
  test/register_label_attr.lean
  test/simpa.lean
  test/solve_by_elim.lean
  test/symm.lean
Labels: awaiting-review

#669 docs: fix documentation build instructions
  README.md
Labels: awaiting-review
