Repository leanprover-community/batteries, pull requests merged in 2024-08, with the labels that each got.

#901 refactor: rename theorems about `Char.utf8Size`
  Batteries/Data/String/Lemmas.lean
Labels: awaiting-review

#906 chore: adaptations for nightly-2024-08-03
  Batteries/Classes/Order.lean
  Batteries/Data/List/EraseIdx.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Pairwise.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/Lean/Util/EnvSearch.lean
  lean-toolchain
Labels: awaiting-review, will-merge-soon

#904 chore: bump lean-action to v1
  .github/workflows/build.yml
  lakefile.lean
Labels: awaiting-review

#903 chore: shake Batteries
  Batteries/CodeAction/Attr.lean
  Batteries/CodeAction/Deprecated.lean
  Batteries/Data/ByteArray.lean
  Batteries/Data/HashMap/Lemmas.lean
  Batteries/Data/HashMap/WF.lean
  Batteries/Data/List/Pairwise.lean
  Batteries/Data/Rat/Basic.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/Data/UnionFind/Basic.lean
  Batteries/Lean/Meta/AssertHypotheses.lean
  Batteries/Lean/Meta/Basic.lean
  Batteries/Lean/Meta/Clear.lean
  Batteries/Lean/Meta/Inaccessible.lean
  Batteries/Lean/Position.lean
  Batteries/Lean/System/IO.lean
  Batteries/Logic.lean
  Batteries/StdDeprecations.lean
  Batteries/Tactic/Case.lean
  Batteries/Tactic/Classical.lean
  Batteries/Tactic/Init.lean
  Batteries/Tactic/NoMatch.lean
  Batteries/Tactic/PrintDependents.lean
  Batteries/Tactic/PrintPrefix.lean
  Batteries/Tactic/SeqFocus.lean
  Batteries/Tactic/ShowUnused.lean
  Batteries/Tactic/Unreachable.lean
  Batteries/Util/Cache.lean
  Batteries/Util/ExtendedBinder.lean
  Batteries/Util/LibraryNote.lean
  test/MLList.lean
Labels: awaiting-review

#889 fix: flaky test
  test/MLList.lean
Labels: awaiting-review

#851 feat: add `ByteSubarray`
  Batteries.lean
  Batteries/Data/ByteSubarray.lean
Labels: awaiting-review

#827 feat: lemmas `List.foldlM_map` and `List.foldrM_map`
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-review

#793 feat: statically sized Vector type
  Batteries.lean
  Batteries/Data/Vector.lean
  Batteries/Data/Vector/Basic.lean
  Batteries/Data/Vector/Lemmas.lean
Labels: awaiting-review

#739 feat: RBMap lemmas
  Batteries/Data/RBMap/Lemmas.lean
Labels: awaiting-review, merge-conflict

#625 feat: add lemma code-action
  Batteries.lean
  Batteries/Tactic/Lemma.lean
  test/lemma_cmd.lean
Labels: awaiting-review

#569 feat: `List.insertP` and lemmas
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Perm.lean
Labels: awaiting-review

#929 chore: make proofs robust to incoming changes
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/String/Lemmas.lean
Labels: will-merge-soon
