Repository leanprover-community/batteries, pull requests merged in 2024-01, with the labels that each got.

#492 feat: add `Nat.one_dvd`, `Nat.dvd_one`, and `Nat.zero_dvd`
  Std/Data/Nat/Lemmas.lean
Labels: awaiting-review

#494 fix: don't panic when linting in empty environments
  GNUmakefile
  Std/Linter/UnreachableTactic.lean
  test/lint_empty.lean
Labels: will-merge-soon

#447 Port: solve_by_elim from Mathlib
  Std.lean
  Std/Control/Nondet/Basic.lean
  Std/Data/MLList/Basic.lean
  Std/Lean/Meta/Basic.lean
  Std/Tactic/SolveByElim.lean
  Std/Tactic/SolveByElim/Backtrack.lean
  test/nondet.lean
  test/solve_by_elim.lean
Labels: will-merge-soon

#481 feat: upstream mathlib definitions used for `ImportGraph`
  Std.lean
  Std/Lean/IO/Process.lean
  Std/Lean/NameMap.lean
  Std/Lean/SMap.lean
Labels: will-merge-soon

#497 feat: array lemmas for append and extract
  Std/Data/Array/Lemmas.lean
  Std/Data/Nat/Lemmas.lean
Labels: will-merge-soon

#487 feat: more simp lemmas for `bind_eq_some`
  Std/Data/Option/Lemmas.lean
Labels: will-merge-soon

#491 feat: three array lemmas
  Std/Data/Array/Lemmas.lean
Labels: will-merge-soon

#505 feat: omega splits Ne
  Std/Tactic/Omega/Frontend.lean
  test/omega/test.lean
Labels: awaiting-review

#507 chore: move MVarId.note
  Std/Lean/Meta/Basic.lean
  Std/Tactic/SolveByElim.lean
Labels: awaiting-review

#486 feat: hover info for `rcases h : ...`
  Std/Tactic/RCases.lean
  lean-toolchain
  test/rcases.lean
Labels: awaiting-review, v4.6.0

#498 chore: Provide consistent Std.Data modules.
  .github/workflows/build.yml
  README.md
  Std.lean
  Std/Data/Array.lean
  Std/Data/BitVec.lean
  Std/Data/Fin.lean
  Std/Data/HashMap.lean
  Std/Data/Int.lean
  Std/Data/List.lean
  Std/Data/MLList.lean
  Std/Data/Nat.lean
  Std/Data/Option.lean
  Std/Data/Prod.lean
  Std/Data/RBMap.lean
  Std/Data/Range.lean
  scripts/check_imports.lean
  scripts/updateStd.sh
Labels: will-merge-soon

#504 feat: omega understands multiplication on the right by a constant
  Std/Tactic/Omega/Coeffs/IntList.lean
  Std/Tactic/Omega/Frontend.lean
  Std/Tactic/Omega/Int.lean
  Std/Tactic/Omega/LinearCombo.lean
  test/omega/test.lean
Labels: will-merge-soon

#514 feat(Data/List): deprecate `last'` and `ilast'`
  Std/Data/List/Basic.lean
  Std/Data/List/Lemmas.lean
Labels: will-merge-soon

#513 doc: how to depend on the library
  README.md
Labels: will-merge-soon

#516 chore: remove unnecessary `have`
  Std/Tactic/Omega/OmegaM.lean
  lean-toolchain
Labels: awaiting-review

#503 feat: omega handles iff and implications
  Std/Logic.lean
  Std/Tactic/FalseOrByContra.lean
  Std/Tactic/Omega/Frontend.lean
  Std/Tactic/Omega/Logic.lean
  test/false_or_by_contra.lean
  test/omega/test.lean
Labels: will-merge-soon

#511 feat: omega understands Prod.Lex
  Std/Data/Prod/Lex.lean
  Std/Tactic/Omega/Frontend.lean
  Std/Tactic/Omega/Int.lean
  test/omega/test.lean
Labels: awaiting-review, depends on another PR

#508 feat: more `ByteArray` lemmas
  Std/Data/ByteArray.lean
Labels: will-merge-soon

#488 feat: add a `TacticM Unit` frontend for omega that can be used as an aesop rule
  Std/Tactic/Omega/Frontend.lean
Labels: will-merge-soon

#521 chore: bump for lean4#3159
  Std/CodeAction/Basic.lean
  Std/Lean/InfoTree.lean
  lean-toolchain
Labels: depends on core changes, v4.6.0

#496 chore: simproc PR changes
  Std/Lean/Meta/Simp.lean
  Std/Tactic/NormCast.lean
  Std/Tactic/SimpTrace.lean
  Std/Tactic/Simpa.lean
  Std/Tactic/SqueezeScope.lean
  lean-toolchain
Labels: will-merge-soon, v4.6.0

#519 feat: `false_or_by_contra` uses `Decidable.byContra` if possible
  Std/Tactic/FalseOrByContra.lean
  Std/Tactic/Omega/Frontend.lean
Labels: will-merge-soon

#465 feat: more lemmas about equality
  Std/Logic.lean
Labels: will-merge-soon

#198 feat: more mul lemmas for `Nat`
  Std/Data/Nat/Lemmas.lean
Labels: awaiting-review

#518 chore: allow omega to use autoparam wrapped hypotheses / consume metadata
  Std/Tactic/Omega/Frontend.lean
  test/omega/test.lean
Labels: will-merge-soon

#522 feat: omega handles double negation and implication hypotheses
  Std/Tactic/FalseOrByContra.lean
  Std/Tactic/Omega/Frontend.lean
  test/false_or_by_contra.lean
  test/omega/test.lean
Labels: awaiting-review

#525 docs: extend docstrings for `ext` and `ext1`
  Std/Tactic/Ext.lean
Labels: awaiting-review

#529 doc: typo in Data.List.Basic
  Std/Data/List/Basic.lean
Labels: awaiting-review

#385 feat: Eq.ndrec lemma
  Std/Logic.lean
Labels: will-merge-soon

#421 Incremental Library Search
  Std.lean
  Std/Lean/Meta/Basic.lean
  Std/Lean/Meta/LazyDiscrTree.lean
  Std/Tactic/LibrarySearch.lean
  Std/Tactic/Relation/Symm.lean
  test/library_search/basic.lean
Labels: will-merge-soon

#536 chore: updates to DiscrTree for changes in nightly
  Std.lean
  Std/Data/BinomialHeap/Basic.lean
  Std/Data/List/Basic.lean
  Std/Lean/Meta/Basic.lean
  Std/Lean/Meta/LazyDiscrTree.lean
  Std/Logic.lean
  Std/Tactic/Ext.lean
  Std/Tactic/LibrarySearch.lean
  Std/Tactic/Relation/Symm.lean
  lean-toolchain
  test/library_search/basic.lean
Labels: awaiting-review, v4.6.0

#537 feat: lemmas about Int divisibility
  Std/Data/Int/DivMod.lean
Labels: awaiting-review

#527 chore: fix isIndependentOf (fixes #424)
  Std/Lean/Meta/Basic.lean
  test/isIndependentOf.lean
Labels: will-merge-soon

#533 chore: reduce imports
  Std/CodeAction/Basic.lean
  Std/CodeAction/Misc.lean
  Std/Control/Nondet/Basic.lean
  Std/Data/Array/Init/Lemmas.lean
  Std/Data/Array/Match.lean
  Std/Data/Json.lean
  Std/Data/List/Basic.lean
  Std/Data/List/Init/Lemmas.lean
  Std/Data/List/Lemmas.lean
  Std/Data/List/Perm.lean
  Std/Data/Option/Basic.lean
  Std/Data/Prod/Lex.lean
  Std/Data/Range/Lemmas.lean
  Std/Data/String/Basic.lean
  Std/Lean/Json.lean
  Std/Lean/Meta/Basic.lean
  Std/Lean/Meta/Inaccessible.lean
  Std/Lean/Meta/Simp.lean
  Std/Lean/Meta/UnusedNames.lean
  Std/Lean/System/IO.lean
  Std/Lean/Util/EnvSearch.lean
  Std/Tactic/Case.lean
  Std/Tactic/FalseOrByContra.lean
  Std/Tactic/Lint/Basic.lean
  Std/Tactic/Omega/Coeffs/IntList.lean
  Std/Tactic/Omega/Constraint.lean
  Std/Tactic/Omega/Core.lean
  Std/Tactic/Relation/Symm.lean
  Std/Tactic/SolveByElim.lean
  Std/Util/ProofWanted.lean
Labels: will-merge-soon

#541 chore: fix missing import in Std.Tactic.LibrarySearch
  Std/Tactic/LibrarySearch.lean
Labels: awaiting-review

#540 fix: make exfalso actually do what it claims to
  Std/Tactic/Basic.lean
  test/exfalso.lean
Labels: awaiting-review

#545 chore: make nightly-testing-YYYY-MM-DD a tag, not a branch
  .github/workflows/nightly_detect_failure.yml
Labels: awaiting-review

#433 Add minWith, maxWith; fix bugs in other min_ and max_ functions.
  Std/Data/Array/Basic.lean
Labels: will-merge-soon

#557 feat: adaptations for leanprover/lean4#3159
  Std/CodeAction/Basic.lean
  Std/Lean/InfoTree.lean
  lean-toolchain
Labels: awaiting-review

#554 feat: better support for 'std_apply? using'
  Std/Tactic/LibrarySearch.lean
  test/library_search/basic.lean
Labels: will-merge-soon

#552 feat: ext lemma for `Char`
  Std/Data/Char.lean
Labels: will-merge-soon

#547 chore: don't call symmSaturate repeatedly in solve_by_elim
  Std/Tactic/SolveByElim.lean
Labels: will-merge-soon

#550 chore: uncomment a test case for solve_by_elim
  test/solve_by_elim.lean
Labels: will-merge-soon

#551 feat: solve_by_elim uses intros and constructor by default
  Std/Tactic/SolveByElim.lean
  test/solve_by_elim.lean
Labels: will-merge-soon

#526 feat: add `ByteArray.ofFn`
  Std/Data/ByteArray.lean
Labels: will-merge-soon

#464 feat: more `Bool` lemmas
  Std/Data/Bool.lean
  Std/Logic.lean
Labels: will-merge-soon

#237 feat: module docs
  Std/Data/Nat/Lemmas.lean
Labels: will-merge-soon

#560 feat: commit `lake-manifest.json`
  .gitignore
  lake-manifest.json
Labels: awaiting-review

#210 feat: upstream addHaveSuggestion and addRewriteSuggestion
  Std.lean
  Std/Lean/Syntax.lean
  Std/Tactic/TryThis.lean
Labels: will-merge-soon

#242 chore: upstream classical tactic
  Std.lean
  Std/Tactic/Classical.lean
  test/classical.lean
Labels: will-merge-soon
