Repository leanprover-community/batteries, pull requests merged in 2024-12, with the labels that each got.

#1070 chore: bump toolchain to v4.14.0
  lean-toolchain
Labels: awaiting-review

#1072 chore: adaptations for nightly-2024-12-01
  Batteries/Data/Array/Basic.lean
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/BinaryHeap.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/FinRange.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/UInt.lean
  Batteries/Data/Vector/Basic.lean
  Batteries/Data/Vector/Lemmas.lean
  BatteriesTest/alias.lean
  BatteriesTest/array.lean
  lean-toolchain
Labels: awaiting-review

#1075 fix: MLList.isEmpty's definition inversed
  Batteries/Data/MLList/Basic.lean
Labels: awaiting-review, builds-mathlib

#1074 refactor: dependent fold for `Fin`
  Batteries/Data/Fin/Basic.lean
  Batteries/Data/Fin/Fold.lean
Labels: awaiting-review, will-merge-soon, builds-mathlib

#966 feat: add `#print opaques` command
  Batteries.lean
  Batteries/Tactic/PrintOpaques.lean
  BatteriesTest/print_opaques.lean
Labels: awaiting-review, will-merge-soon, builds-mathlib
