Repository leanprover-community/batteries, pull requests merged in 2024-06, with the labels that each got.

#796 chore: align `isInternalName` with upstream version
  Batteries/Lean/Name.lean
Labels: awaiting-review, will-merge-soon

#818 chore: manifest out of date doesn't count as test noise
  scripts/test.lean
Labels: awaiting-review, will-merge-soon

#820 chore: add `@[simp]` for `Fin.foldl_zero` and `Fin.foldr_zero`
  Batteries/Data/Fin/Lemmas.lean
Labels: awaiting-review

#819 feat: add lemma `Fin.list_reverse`
  Batteries/Data/Fin/Lemmas.lean
Labels: awaiting-review

#825 chore: adaptations for nightly-2024-06-06
  Batteries/CodeAction/Deprecated.lean
  Batteries/Data/ByteArray.lean
  Batteries/Data/Fin/Basic.lean
  Batteries/Data/Fin/Lemmas.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/Lean/Delaborator.lean
  Batteries/Tactic/Instances.lean
  Batteries/Tactic/PrintDependents.lean
  Batteries/Tactic/PrintPrefix.lean
  Batteries/Tactic/ShowUnused.lean
  lakefile.lean
  lean-toolchain
Labels: will-merge-soon

#830 feat: missing modifyNth simp lemmas
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-review, will-merge-soon

#829 feat: `measureRec` for strong induction use cases
  Batteries/Data/Nat/Basic.lean
Labels: awaiting-review, will-merge-soon

#833 chore: squeeze simps in HashMap.WF
  Batteries/Data/HashMap/WF.lean
Labels: will-merge-soon

#834 chore(RBSet): consolidate API from mathlib
  Batteries/Data/RBMap/Basic.lean
Labels: will-merge-soon

#837 chore: adaptations for nightly-2024-06-11
  Batteries/Data/Char.lean
  Batteries/Data/String/Lemmas.lean
  lean-toolchain
Labels: awaiting-review, will-merge-soon

#839 chore(Tactic/Lint/Simp): make simpNF linter dsimp-aware
  Batteries/Tactic/Lint/Simp.lean
  test/lint_simpNF.lean
Labels: awaiting-review

#842 feat: ext lemma for `Thunk`
  Batteries.lean
  Batteries/Data/Thunk.lean
Labels: awaiting-review

#846 chore: remove docgen from the manifest
  lake-manifest.json
Labels: will-merge-soon

#847 chore: bump toolchain to v4.9.0-rc2
  lean-toolchain
Labels: awaiting-review

#844 Reapply "chore(Tactic/Lint/Simp): make simpNF linter dsimp-aware (#839)" (#841)
  Batteries/Tactic/Lint/Simp.lean
  test/lint_simpNF.lean
Labels: awaiting-review

#849 feat: add `BinaryHeap`
  Batteries.lean
  Batteries/Data/BinaryHeap.lean
Labels: awaiting-review

#848 chore: adaptations for nightly-2024-06-16
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/Fin/Lemmas.lean
  Batteries/Data/HashMap/WF.lean
  Batteries/Data/List/EraseIdx.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Pairwise.lean
  Batteries/Tactic/Lint/Simp.lean
  lake-manifest.json
  lean-toolchain
  test/congr.lean
  test/lint_simpNF.lean
Labels: awaiting-review, will-merge-soon

#852 chore: robust proof in HashMap.WF.filterMap
  Batteries/Data/HashMap/WF.lean
Labels: awaiting-review

#853 feat: add simps and `toNat` lemmas for `UIntX` types
  Batteries/Data/UInt.lean
Labels: awaiting-review

#858 chore: bump toolchain to v4.9.0-rc3
  lean-toolchain
Labels: will-merge-soon

#861 chore: `unreachableTactic` -- replace a `Std` namespace with `Batteries` and add an `inherit_doc`.
  Batteries/Linter/UnreachableTactic.lean
Labels: awaiting-review

#864 chore: avoid nonterminal simps in String/Lemmas
  Batteries/Data/String/Lemmas.lean
  Batteries/Linter/UnnecessarySeqFocus.lean
  Batteries/Linter/UnreachableTactic.lean
  lean-toolchain
Labels: awaiting-review
