Repository leanprover-community/batteries, pull requests merged in 2025-09, with the labels that each got.

#1308 feat: add `@[simp]` lemma `WellFounded.val_wrap`
  Batteries/WF.lean
Labels: awaiting-review, breaks-mathlib

#1405 feat: more support for `AlternativeMonad`
  Batteries/Control/Nondet/Basic.lean
  Batteries/Data/MLList/Basic.lean
  Batteries/Lean/Meta/Basic.lean
  BatteriesTest/nondet.lean
Labels: awaiting-review, builds-mathlib

#1406 feat: lemmas about `throw` and `tryCatch` for `ReaderT` and `StateT`
  Batteries/Control/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1344 feat: add `Char.all`, `Char.any` and decidability instances
  Batteries/Data/Char/Basic.lean
Labels: awaiting-review, builds-mathlib

#1413 chore: bump toolchain to v4.23.0
  lean-toolchain
Labels: awaiting-review
