Repository leanprover-community/batteries, pull requests merged in 2025-07, with the labels that each got.

#1303 chore: `@[grind]` annotations for `BitVec` lemmas
  Batteries/Data/BitVec/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1302 chore: `@[grind]` annotations for `Array` lemmas
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/Array/Pairwise.lean
Labels: awaiting-review, builds-mathlib

#1305 fix: nightly testing zulip message
  .github/workflows/nightly_detect_failure.yml
Labels: awaiting-review

#1294 feat: make `unusedHavesSuffices` linter only apply to propositions
  Batteries/Tactic/Lint/Misc.lean
Labels: awaiting-review, builds-mathlib

#1314 chore: bump toolchain to v4.22.0-rc3
  BatteriesTest/instances.lean
  lean-toolchain
Labels: awaiting-review

#1267 feat: lemmas about `Nat.toDigits`
  Batteries/Data/Nat.lean
  Batteries/Data/Nat/Digits.lean
Labels: awaiting-review, builds-mathlib

#1313 feat: Laws for `MonadStateOf` instances
  Batteries.lean
  Batteries/Control/LawfulMonadState.lean
  Batteries/Control/OptionT.lean
Labels: awaiting-review, will-merge-soon, builds-mathlib

#1333 feat: add ASCII character casing lemmas
  Batteries/Data/Char.lean
Labels: awaiting-review, will-merge-soon, builds-mathlib

#1341 chore: bump toolchain to v4.22.0-rc4
  lean-toolchain
Labels: awaiting-review

#1343 chore: reorganize `Data.Char`
  Batteries/Data/Char.lean
  Batteries/Data/Char/AsciiCasing.lean
  Batteries/Data/Char/Basic.lean
Labels: awaiting-review, builds-mathlib

#1337 feat: lemmas about running `EStateM` computations
  Batteries/Lean/EStateM.lean
Labels: awaiting-review, builds-mathlib

#1348 chore: avoid TransOrd String instance name collision
  Batteries/Data/String/Lemmas.lean
  scripts/noshake.json
Labels: awaiting-review

#1357 chore: remove >6 month deprecations
  Batteries/Data/Fin/Fold.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Perm.lean
  Batteries/Data/Range/Lemmas.lean
Labels: awaiting-review, builds-mathlib
