Repository leanprover-community/batteries, pull requests merged in 2025-03, with the labels that each got.

#1098 feat: add lemmas for List.isPrefixOf? and List.isSuffixOf?
  Batteries/Data/List/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1150 chore: bump toolchain to v4.17.0
  lean-toolchain
Labels: awaiting-review

#1078 feat: add BitVec.ofFn and lemmas
  Batteries.lean
  Batteries/Data/BitVec.lean
  Batteries/Data/BitVec/Basic.lean
  Batteries/Data/BitVec/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1155 doc: Fix typo
  Batteries/Data/List/Basic.lean
Labels: awaiting-review, builds-mathlib

#1148 chore: remove vestigial file scripts/test.lean
  scripts/test.lean
Labels: awaiting-review, builds-mathlib

#1164 chore: remove >6 month old deprecations
  Batteries.lean
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/ByteArray.lean
  Batteries/Data/Char.lean
  Batteries/Data/LazyList.lean
  Batteries/Data/List.lean
  Batteries/Data/List/EraseIdx.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/String/Lemmas.lean
Labels: awaiting-review

#1166 doc: Mathlib adaptation process
  README.md
Labels: documentation, will-merge-soon, builds-mathlib

#1172 chore(Classes/SatisfiesM): generalize `Applicative` -> `Functor`
  Batteries/Classes/SatisfiesM.lean
Labels: awaiting-review

#1171 chore: generalize `TransCmp` -> `OrientedCmp`
  Batteries/Classes/Order.lean
  Batteries/Data/RBMap/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1181 chore: adjust cron jobs for nightly-testing
  .github/workflows/nightly_bump_toolchain.yml
Labels: awaiting-review

#1063 chore: replace Batteries.HashMap with a shim around Std.HashMap
  Batteries/Data/HashMap.lean
  Batteries/Data/HashMap/Basic.lean
  Batteries/Data/HashMap/Lemmas.lean
  Batteries/Data/HashMap/WF.lean
Labels: awaiting-review, builds-mathlib
