Repository leanprover-community/batteries, pull requests merged in 2025-08, with the labels that each got.

#1359 fix: use `semiOutParam` in `LawfulMonadState`
  Batteries/Control/LawfulMonadState.lean
Labels: awaiting-review, builds-mathlib

#1306 chore: deprecate old comparison classes
  Batteries.lean
  Batteries/Classes/Deprecated.lean
  Batteries/Classes/Order.lean
  Batteries/Data/Char/Basic.lean
  Batteries/Data/RBMap/Alter.lean
  Batteries/Data/RBMap/Basic.lean
  Batteries/Data/RBMap/Lemmas.lean
  Batteries/Data/RBMap/WF.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/Data/UInt.lean
Labels: awaiting-review, builds-mathlib

#1307 feat: add code action to generate `match` cases
  Batteries.lean
  Batteries/CodeAction.lean
  Batteries/CodeAction/Match.lean
Labels: awaiting-review, will-merge-soon, builds-mathlib

#1349 feat: add Hashable instance to Rat
  Batteries/Data/Rat/Basic.lean
Labels: awaiting-review, breaks-mathlib

#1369 chore: propose deprecation of List.fillNones
  Batteries/Data/List/Basic.lean
Labels: awaiting-review, builds-mathlib

#1377 chore: replace a `let` with `have`
  Batteries/Data/Nat/Gcd.lean
Labels: awaiting-review, breaks-mathlib

#1379 chore: bump toolchain to v4.23.0-rc2
  lean-toolchain
Labels: awaiting-review

#1380 remove `Std` imports that are now in `Init`
  Batteries/Data/Char/AsciiCasing.lean
  Batteries/Data/String/Lemmas.lean
Labels: awaiting-review

#1395 feat: better Newton starting point in `Nat.sqrt`
  Batteries/Data/Nat/Basic.lean
Labels: awaiting-review, builds-mathlib
