Repository leanprover-community/batteries, pull requests merged in 2025-04, with the labels that each got.

#1184 chore: bump toolchain to v4.18.0
  lean-toolchain
Labels: awaiting-review

#1186 chore: bump toolchain to v4.19.0-rc1
  Batteries/Classes/SatisfiesM.lean
  Batteries/Data/AssocList.lean
  Batteries/Data/ByteArray.lean
  Batteries/Data/HashMap/Basic.lean
  Batteries/Data/HashMap/Lemmas.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Monadic.lean
  Batteries/Data/List/Pairwise.lean
  Batteries/Data/List/Perm.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/Lean/Expr.lean
  Batteries/Linter/UnreachableTactic.lean
  Batteries/Tactic/Alias.lean
  Batteries/Tactic/PrintPrefix.lean
  Batteries/Tactic/Trans.lean
  Batteries/WF.lean
  BatteriesTest/help_cmd.lean
  BatteriesTest/print_prefix.lean
  lean-toolchain
  scripts/runLinter.lean
Labels: awaiting-review

#1188 chore: bump toolchain to v4.19.0-rc2
  Batteries/Data/Nat/Gcd.lean
  Batteries/Data/Nat/Lemmas.lean
  lean-toolchain
Labels: awaiting-review, breaks-mathlib

#1190 fix: use loadExts := true in runLinter
  scripts/runLinter.lean
Labels: awaiting-review

#1192 chore: copy merge-lean-testing-pr script from Mathlib
  scripts/merge-lean-testing-pr.sh
Labels: awaiting-review

#1194 chore: mark `Nat.sqrt.iter` as semireducible
  Batteries/Data/Nat/Basic.lean
Labels: awaiting-review, builds-mathlib

#1197 fix: use a one-field structure for `Batteries.HashMap`
  Batteries/Data/HashMap/Basic.lean
Labels: awaiting-review, builds-mathlib

#1201 chore: deprecate mis-cased Lean.MVarId.assignIfDefeq
  Batteries/Tactic/Exact.lean
Labels: awaiting-review, builds-mathlib
