Repository leanprover-community/batteries, pull requests merged in 2025-01, with the labels that each got.

#1080 chore: bump toolchain to v4.15.0
  lean-toolchain
Labels: awaiting-review

#1081 chore: bump toolchain to v4.16.0-rc1
  Batteries.lean
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/Char.lean
  Batteries/Data/HashMap/WF.lean
  Batteries/Data/PairingHeap.lean
  Batteries/Data/Range/Lemmas.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/Data/UnionFind/Basic.lean
  Batteries/Tactic/Where.lean
  BatteriesTest/where.lean
  lean-toolchain
Labels: awaiting-review

#1083 fix: remove docs lake manifest
  docs/lake-manifest.json
Labels: awaiting-review

#984 feat: add Mersenne Twister PRNG
  Batteries.lean
  Batteries/Data/Random.lean
  Batteries/Data/Random/MersenneTwister.lean
  BatteriesTest/mersenne_twister.lean
Labels: awaiting-review, will-merge-soon, builds-mathlib

#1084 chore: post reminder to create adaptation PR
  .github/workflows/nightly_detect_failure.yml
Labels: awaiting-review

#1085 chore: add adaptation PR helper script
  scripts/create-adaptation-pr.sh
Labels: awaiting-review

#1087 fix: don't build multiple times
  .github/workflows/build.yml
Labels: awaiting-review

#1086 fix: make lake preserve toolchain for docs
  .github/workflows/docs-deploy.yml
  .github/workflows/docs-release.yml
Labels: awaiting-review

#1090 feat: add List.toArrayMap
  Batteries/Data/List.lean
  Batteries/Data/List/ArrayMap.lean
  BatteriesTest/ArrayMap.lean
  scripts/test.lean
Labels: awaiting-review, builds-mathlib

#1091 feat: add further API about `Lean.NameSet`
  Batteries.lean
  Batteries/Data/NameSet.lean
Labels: awaiting-review, breaks-mathlib

#1093 chore: bump to v4.16.0-rc2
  lean-toolchain
Labels: awaiting-review

#1089 feat: add `Nat.ofBits` and `Fin.ofBits`
  Batteries/Data/Fin.lean
  Batteries/Data/Fin/OfBits.lean
  Batteries/Data/Nat/Basic.lean
  Batteries/Data/Nat/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1100 fix: don't build multiple times
  .github/workflows/build.yml
Labels: awaiting-review

#1101 feat: prove `Array.toList_erase`
  Batteries/Data/Array/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1096 feat: add `Int.ofBits`
  Batteries.lean
  Batteries/Data/Int.lean
Labels: awaiting-review, builds-mathlib

#1104 feat: add `LawfulBEq` instance for `Vector`
  Batteries/Data/Vector/Basic.lean
  Batteries/Data/Vector/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1108 feat: better implementation of `ByteArray.ofFn`
  Batteries/Data/ByteArray.lean
Labels: awaiting-review, builds-mathlib

#1110 fix: delete obsolete `csimp`
  Batteries/Data/ByteArray.lean
Labels: awaiting-review
