Repository leanprover-community/batteries, pull requests merged in 2025-05, with the labels that each got.

#1217 chore: bump toolchain to v4.19.0
  BatteriesTest/by_contra.lean
  lean-toolchain
Labels: awaiting-review

#1219 chore: bump toolchain to v4.20.0-rc1
  Batteries/Control/AlternativeMonad.lean
  Batteries/Data/BitVec/Lemmas.lean
  Batteries/Data/Fin/Lemmas.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/Nat/Gcd.lean
  Batteries/Data/RBMap/Lemmas.lean
  Batteries/Data/Rat/Basic.lean
  Batteries/Data/Rat/Lemmas.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/Tactic/Lint/Frontend.lean
  BatteriesTest/instances.lean
  BatteriesTest/simp_trace.lean
  lean-toolchain
Labels: awaiting-review, breaks-mathlib

#1221 chore: bump toolchain to v4.20.0-rc2
  lean-toolchain
Labels: awaiting-review, breaks-mathlib

#1225 perf: make `Rat` use `divExact` for normalization
  Batteries/Data/Rat/Basic.lean
  Batteries/Data/Rat/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1199 chore: deprecate Batteries.HashMap
  Batteries/Data/HashMap/Basic.lean
Labels: awaiting-review, builds-mathlib

#1230 chore: add note about Std.TreeMap in RBMap module doc
  Batteries/Data/RBMap/Basic.lean
Labels: awaiting-review, builds-mathlib

#1234 feat: add `Vector.tail` API
  Batteries/Data/Vector/Lemmas.lean
Labels: will-merge-soon, builds-mathlib

#1236 fix: Rename `tail` lemmas
  Batteries/Data/Vector/Lemmas.lean
Labels: awaiting-author, builds-mathlib

#1239 feat: port 'discover-lean-pr-testing.yml' to Batteries
  .github/workflows/discover-lean-pr-testing.yml
Labels: will-merge-soon, builds-mathlib
