Repository leanprover-community/batteries, pull requests merged in 2025-02, with the labels that each got.

#1112 chore: remove meta results for README `proof_wanted` link
  README.md
Labels: awaiting-review, builds-mathlib

#1113 chore: bump toolchain to v4.16.0
  lean-toolchain
Labels: awaiting-review

#1115 chore: bump toolchain to v4.17.0-rc1
  Batteries/Classes/Order.lean
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/Array/Monadic.lean
  Batteries/Data/ByteArray.lean
  Batteries/Data/List/Basic.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/List/Perm.lean
  Batteries/Data/RBMap/Lemmas.lean
  Batteries/Data/String/Lemmas.lean
  Batteries/Data/Vector.lean
  Batteries/Data/Vector/Basic.lean
  Batteries/Data/Vector/Lemmas.lean
  Batteries/Data/Vector/Monadic.lean
  Batteries/Lean/System/IO.lean
  Batteries/Linter/UnreachableTactic.lean
  Batteries/Tactic/Lint/TypeClass.lean
  Batteries/Tactic/OpenPrivate.lean
  lean-toolchain
Labels: breaks-mathlib

#1117 chore: update nightly-testing bot
  .github/workflows/nightly_detect_failure.yml
Labels: awaiting-review

#1118 chore: fix typo in nightly_detect_failure.yml
  .github/workflows/nightly_detect_failure.yml
Labels: awaiting-review

#1119 chore: bug in nightly_detect_failure.yml
  .github/workflows/nightly_detect_failure.yml
Labels: awaiting-review

#1120 chore: bug in nightly_detect_failure.yml
  .github/workflows/nightly_detect_failure.yml
Labels: awaiting-review

#1109 feat: proofs for Batteries.Data.Array/Vector.Monadic
  Batteries.lean
  Batteries/Control/Monad.lean
  Batteries/Data/Array/Monadic.lean
  Batteries/Data/Vector/Monadic.lean
Labels: awaiting-review

#1116 fix: use ext attribute to generate ext lemmas for `ByteArray` and `FloatArray`
  Batteries/Data/ByteArray.lean
  Batteries/Data/FloatArray.lean
Labels: awaiting-review, builds-mathlib

#1125 feat: add `LawfulMonadLift`
  Batteries.lean
  Batteries/Control/Lawful/MonadLift.lean
  Batteries/Lean/LawfulMonadLift.lean
Labels: awaiting-review, builds-mathlib

#1129 chore: fix simp direction for `monadLift_bind`
  Batteries/Control/Lawful/MonadLift.lean
Labels: awaiting-review, builds-mathlib

#1135 chore: revert accidental commit to `main`
  Batteries/Logic.lean
Labels: awaiting-review

#1130 chore: remove explicit universes from `EStateM` results
  Batteries/Lean/EStateM.lean
Labels: awaiting-review, builds-mathlib

#1136 chore(Logic): give implicit argument an accessible name
  Batteries/Logic.lean
Labels: awaiting-review, builds-mathlib

#1099 feat: add `Fin.find?`, `Fin.findSome?` and lemmas
  Batteries/Data/Fin/Basic.lean
  Batteries/Data/Fin/Lemmas.lean
Labels: awaiting-review, builds-mathlib
