Repository leanprover-community/batteries, pull requests merged in 2025-06, with the labels that each got.

#1251 chore: deprecate LawfulHashable
  Batteries/Data/HashMap/Basic.lean
Labels: will-merge-soon, builds-mathlib

#1260 chore: bump toolchain to v4.21.0-rc3
  lean-toolchain
Labels: awaiting-review

#1220 feat: simpNF to check lemmas with conditions
  Batteries/Data/BinomialHeap/Lemmas.lean
  Batteries/Tactic/Lint/Simp.lean
Labels: awaiting-review, builds-mathlib

#1266 fix(simpNF): use correct Meta configuration
  Batteries/Tactic/Lint/Simp.lean
  BatteriesTest/lint_simpNF.lean
Labels: awaiting-review, builds-mathlib

#1268 fix: use lakefile.toml instead of lakefile.lean in discover workflow
  .github/workflows/discover-lean-pr-testing.yml
Labels: awaiting-review

#1263 fix: do not create Decidable subgoals from by_contra
  Batteries/Tactic/Init.lean
  BatteriesTest/by_contra.lean
Labels: will-merge-soon, builds-mathlib

#1262 chore(Data/Vector): lemmas about finIdxOf?
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/Vector/Lemmas.lean
Labels: awaiting-review, builds-mathlib

#1281 chore: mathlib now uses forks same as here
  README.md
Labels: will-merge-soon, builds-mathlib

#1287 chore: update CI to use mathlib4-nightly-testing fork
  .github/workflows/test_mathlib.yml
Labels: awaiting-review, builds-mathlib

#1292 fix batteries after Subarray->Slice migration
  Batteries/Data/Array/Basic.lean
Labels: awaiting-review

#1299 chore: bump toolchain to v4.22.0-rc1
  Batteries/Classes/SatisfiesM.lean
  Batteries/Data/Array/Basic.lean
  Batteries/Data/Array/Lemmas.lean
  Batteries/Data/BitVec/Lemmas.lean
  Batteries/Data/List/Lemmas.lean
  Batteries/Data/UInt.lean
  Batteries/Lean/Meta/Simp.lean
  Batteries/Linter/UnnecessarySeqFocus.lean
  Batteries/Tactic/Alias.lean
  Batteries/Tactic/Lint/Basic.lean
  Batteries/Tactic/Lint/Frontend.lean
  Batteries/Tactic/Lint/Misc.lean
  Batteries/Tactic/SqueezeScope.lean
  BatteriesTest/alias.lean
  BatteriesTest/help_cmd.lean
  BatteriesTest/lintTC.lean
  BatteriesTest/lint_simpNF.lean
  BatteriesTest/lint_unreachableTactic.lean
  BatteriesTest/simpa.lean
  lakefile.toml
  lean-toolchain
Labels: awaiting-review, breaks-mathlib
